kind: Deployment
apiVersion: apps/v1
metadata:
 name: nodered-deploy
spec:
 replicas: 1
 selector:
  matchLabels: 
   app: nodered-deploy
 template:
  metadata:
   labels:
    app: nodered-deploy
  spec:
   containers:
   - name: nodered-https
     image: gcr.io/synapses-323217/github.com/misbahhassan08/nodered-https:latest
     ports:
     - containerPort: 1880
---
apiVersion: v1 
kind: Service
metadata:
 name: nodered-svc
spec:
 type: NodePort
 selector:
  app: nodered-deploy
 ports:
 - name: http
   port: 80
   targetPort: 1880
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: nodered-ingress
 annotations:
  kubernetes.io/ingress.global-static-ip-name: irobotx-ip
  networking.gke.io/managed-certificates: managed-cert-nodered
  kubernetes.io/ingress.class: "gce"
spec:
 defaultBackend:
  service:
   name: nodered-svc
   port:
    number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert-nodered
spec:
  domains:
    - irobotx.34.117.248.236.nip.io
